[package]
name = "incremental-society"
version = "0.1.0"
authors = ["Chris Hamons <chris.hamons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.5"
console = "0.9.1"
num-traits = "0.2"
num-derive = "0.3"